apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-deployment
  labels:
    app: hello
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
      - name: hello-container
        image: 891376968724.dkr.ecr.us-east-1.amazonaws.com/app/htmlapp:latest
        ports:
        - containerPort: 80
