apiVersion: apps/v1
kind: Deployment
metadata:
  name: htmlapp-deployment
  labels:
    app: htmlapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: htmlapp
  template:
    metadata:
      labels:
        app: htmlapp
    spec:
      containers:
      - name: htmlapp-container
        # Use a imagem do ECR
        image: 891376968724.dkr.ecr.us-east-1.amazonaws.com/app/htmlapp:latest
        ports:
        - containerPort: 80
