apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
images:
  - name: 891376968724.dkr.ecr.us-east-1.amazonaws.com/app/htmlapp
    newTag: latest
